[package]
name = "yalc"
version = "0.1.0"
edition = "2021"
description = "Yet Another Logging Crate"
license = "MIT"
repository = "https://github.com/KeiranScript/yalc"
readme = "README.md"
homepage = "https://github.com/KeiranScript/yalc"

[dependencies]

[[example]]
name = "main"
